version: '3.4'

services:
  bytebank:
    image: bytebank
    build: .
    ports:
      - 4200:80
  dados:
    image: bytebank-dados
    build: 
      context: .
      dockerfile: Dockerfile-dados
    ports:
      - 3000:80
